### ISSUE TITLE
关于报文总长度太大、有效报文太短而导致过度浪费系统资源的问题

### ISSUE THREAD

**Issue by SexyCrane** [kerryjiang/SuperSocket#232]
你好，非常感谢你的项目，让我的TCP服务方便了很多，但是我在使用的过程中发现一个情况：报文长度默认是4096，Filter(byte[] readBuffer, int offset, int length, bool toBeCopied, out int rest)方法中readBuffer的总长度是ReceiveBufferSize的1000倍，ReceiveBufferSize是length的最大值，那么为什么要把readBuffer设置成ReceiveBufferSize的1000倍呢？这样浪费了大量的系统资源，导致我接受报文的时候经常是skip几乎所有的报文，然后take最后几个字节，随着客户端数量增加，服务器CPU几度飙升几近崩溃，请问readBuffer最大值可以修改吗，根据自己的需求改小点，节约一下系统资源，非常感谢！

**Comment by chucklu** [comment]
Please read the documentation http://docs.supersocket.net/v1-6/en-US/SuperSocket-Basic-Configuration

> **Servers Configuration**
> receiveBufferSize: receiving buffer size;
> sendBufferSize: sending buffer size;

**Comment by SexyCrane** [comment]
![image](https://user-images.githubusercontent.com/18661721/61218952-c028eb80-a745-11e9-8065-a9b8fffe86e4.png)
![image](https://user-images.githubusercontent.com/18661721/61218968-c6b76300-a745-11e9-9d57-ef10fe56c329.png)
你好，不好意思，我能看懂你的英文，但是我自己不太太会用英文回复。
我看了文档的，我上面的截图您看一下，我设置了ReceiveBufferSize是1000，但是在接收消息后Filter里面第一个参数readBuffer的长度是10000000，所以我要skip前9999000才能拿到我要的数据，而skip是很耗系统资源的，而且这个操作并不是必须的，所以readBuffer的长度是否可以设置短一点，这样就能节约很多系统资源

**Comment by chucklu** [comment]
I did not have time to do the troubleshooting for you, but I suggest you consider to do the configuration through app.config file instead of through code.
You can refer to the quick start demo https://github.com/kerryjiang/SuperSocket/blob/v1.6/QuickStart/Basic/TelnetServer_StartByConfig/App.config
https://github.com/kerryjiang/SuperSocket.Document/blob/v1.6(zh-CN)/030-Start-SuperSocket-by-Configuration.md

**Comment by SexyCrane** [comment]
我找到问题所在了，里面有个BufferManager，会一直占用MaxConnectionNumber*ReceiveBufferSize的大小
