### ISSUE TITLE
netstandard2.0兼容问题

### ISSUE THREAD

**Issue by cocosip** [kerryjiang/SuperSocket#294]
新版的supersocket 使用的是 netstandard2.1的版本, 目前我们还有一部分的程序都是基于 .net core 2.x的。这块的兼容要怎么做呢？

**Comment by geffzhang** [comment]
最低要求是netstandard2.1了，使用了很多.net core 2.x不支持的特性， 建议升级到.net core 3.1

**Comment by cocosip** [comment]
> 最低要求是netstandard2.1了，使用了很多.net core 2.x不支持的特性， 建议升级到.net core 3.1
我们正在迁移现在的一些程序到 core3.1。
之前用的都是DotNetty, 花了一些时间去研究。结果DotNetty就这样烂尾了... 想找个新的Socket库代替,目前看到比较好的也就SuperSocket,之前有关注但是还未深入研究。

**Comment by kerryjiang** [comment]
比较关键的新特性依赖于netstandard2.1, 所以没办法。你的入后项目是.NET Core 3.1, 他依赖的项目可以netstandard2.0或者更低。

**Comment by chucklu** [comment]
https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/

Given many of the API additions in .NET Standard 2.1 require runtime changes in order to be meaningful, .NET Framework 4.8 will remain on .NET Standard 2.0 rather than implement .NET Standard 2.1. .NET Core 3.0 as well as upcoming versions of Xamarin, Mono, and Unity will be updated to implement .NET Standard 2.1.

**Library authors who need to support .NET Framework customers should stay on .NET Standard 2.0.** In fact, most libraries should be able to stay on .NET Standard 2.0, as the API additions are largely for advanced scenarios. However, this doesn’t mean that library authors cannot take advantage of these APIs even if they have to support .NET Framework. **In those cases they can use multi-targeting to compile for both .NET Standard 2.0 as well as .NET Standard 2.1.** This allows writing code that can expose more features or provide a more efficient implementation on runtimes that support .NET Standard 2.1 while not giving up on the bigger reach that .NET Standard 2.0 offers.

**Comment by cocosip** [comment]
已升级项目
